date.timezone = UTC
upload_max_filesize = 25M
post_max_size = 25M
max_execution_time = 1800
max_input_time = 1800
memory_limit = 512M

# OPcache dezactivat - recomandat de WHMCS
opcache.enable = 0
opcache.enable_cli = 0
