#!/usr/bin/with-contenv bash

# Configure php-fpm php config
cp -vf /defaults/php/* /etc/php/${PHP_VERSION}/fpm/conf.d/

# Configure php-fpm globals & pool
cp -vf /defaults/fpm/* /etc/php/${PHP_VERSION}/fpm/pool.d/

# Create override for local.ini if it doesn't exist, set local timezone
mkdir -p \
  /config/php/
[[ ! -f /config/php/99-local.ini ]] && \
    printf "; Edit this file to override php.ini directives and restart the container\\n\\ndate.timezone = %s\\n" "$TZ" > /config/php/99-local.ini
chown abc:abc -R /config/php/

# Copy user 99-local.ini to image
cp -vf /config/php/99-local.ini /etc/php/${PHP_VERSION}/fpm/conf.d/99-local.ini

# Create override for local.conf if it doesn't exist
mkdir -p \
  /config/fpm/
[ ! -f /config/fpm/99-local.conf ] && \
    printf "; Edit this file to override www.conf and php-fpm.conf directives and restart the container\\n\\n; Pool name\\n[www]\\n\\n" > /config/fpm/99-local.conf
chown abc:abc -R /config/fpm/

# Copy user 99-local.conf to image
cp -vf /config/fpm/99-local.conf /etc/php/${PHP_VERSION}/fpm/pool.d/99-local.conf
